import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ComponentResolver } from 'unplugin-vue-components';
import { getLibraryUserConfig } from '@/config';
import { getLibraryConfig } from '@/libraries';
import * as presets from '../presets';
import type { UiEnhanceOptions, UiLibrary, UiLibraryConfig, UiRule, UiRules } from '@/types';

const __dirname = path.dirname(fileURLToPath((import.meta as { url: string }).url));
const packageJsonPath = path.resolve(__dirname, '../../package.json');
let packageName = 'ui-auto-specification';

try {
  if (fs.existsSync(packageJsonPath)) {
    const file = fs.readFileSync(packageJsonPath, 'utf-8');
    const pkg = JSON.parse(file) as { name?: string };
    if (typeof pkg.name === 'string') {
      packageName = pkg.name;
    }
  }
} catch {
  // 当package.json不可用时回退到默认名称
}

const DEFAULT_CACHE_DIR = path.resolve(
  process.cwd(),
  'node_modules/.cache/ui-auto-specification/.enhanced'
);
const ENHANCED_DIR = process.env.UI_AUTO_SPECIFICATION_CACHE_DIR ?? DEFAULT_CACHE_DIR;

function getPresetRules(library: UiLibrary): UiRules {
  const presetMap: Record<UiLibrary, UiRules> = {
    vant: presets.VantPreset,
    'element-plus': presets.ElementPlusPreset,
    'naive-ui': presets.NaiveUiPreset,
    varlet: presets.VarletPreset,
    'ant-design-vue': presets.AntDesignVuePreset
  };
  return presetMap[library] ?? {};
}

function ensureCacheDir() {
  if (!fs.existsSync(ENHANCED_DIR)) {
    fs.mkdirSync(ENHANCED_DIR, { recursive: true });
  }
}

function indentMultiline(value: string, indent = 2): string {
  const pad = ' '.repeat(indent);
  return value
    .split('\n')
    .map((line, index) => (index === 0 ? line : pad + line))
    .join('\n');
}

function serializeRule(rule: UiRule): string {
  const segments: string[] = [];

  if (rule.defaults) {
    segments.push(`  defaults: ${indentMultiline(JSON.stringify(rule.defaults, null, 2))}`);
  }

  if (typeof rule.autoPlaceholder === 'function') {
    segments.push(`  autoPlaceholder: ${indentMultiline(rule.autoPlaceholder.toString())}`);
  } else if (rule.autoPlaceholder !== undefined) {
    segments.push(`  autoPlaceholder: ${JSON.stringify(rule.autoPlaceholder)}`);
  }

  if (typeof rule.transform === 'function') {
    segments.push(`  transform: ${indentMultiline(rule.transform.toString())}`);
  }

  if (!segments.length) {
    return '{}';
  }

  return `{
${segments.join(',\n')}
}`;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isUiRule(value: unknown): value is UiRule {
  if (!isPlainObject(value)) return false;
  if ('defaults' in value && value.defaults !== undefined && !isPlainObject(value.defaults)) return false;
  if ('autoPlaceholder' in value) {
    const auto = value.autoPlaceholder;
    if (auto !== undefined && typeof auto !== 'boolean' && typeof auto !== 'function') {
      return false;
    }
  }
  if ('transform' in value) {
    const transform = value.transform;
    if (transform !== undefined && typeof transform !== 'function') {
      return false;
    }
  }
  return true;
}

function isUiRules(value: unknown): value is UiRules {
  if (!isPlainObject(value)) return false;
  return Object.values(value).every(isUiRule);
}

interface LibraryOverrides {
  rules?: UiRules;
  usePreset?: boolean;
}

function toLibraryOverrides(value: unknown): LibraryOverrides | undefined {
  if (!isPlainObject(value)) {
    return undefined;
  }

  const normalized: LibraryOverrides = {};
  let hasOverride = false;

  if ('rules' in value) {
    const maybeRules = value.rules;
    if (isUiRules(maybeRules)) {
      normalized.rules = maybeRules;
      hasOverride = true;
    }
  }

  if ('usePreset' in value) {
    const maybeUsePreset = value.usePreset;
    if (typeof maybeUsePreset === 'boolean') {
      normalized.usePreset = maybeUsePreset;
      hasOverride = true;
    }
  }

  return hasOverride ? normalized : undefined;
}

function createEnhancedComponent(componentName: string, rule: UiRule, libraryConfig: UiLibraryConfig): string {
  let importName: string;
  if (libraryConfig.exportPrefix === false) {
    importName = componentName.replace(new RegExp(`^${libraryConfig.prefix}`), '');
  } else if (typeof libraryConfig.exportPrefix === 'string') {
    importName = componentName;
  } else if (typeof libraryConfig.exportPrefix === 'function') {
    importName = libraryConfig.exportPrefix(componentName);
  } else {
    importName = componentName;
  }

  ensureCacheDir();

  const filePath = path.join(ENHANCED_DIR, `${componentName}.ts`);
  const code = `// Auto-generated by ui-auto-specification\nimport { ${importName} } from '${libraryConfig.packageName}';\nimport { withUiRules } from '${packageName}/runtime';\n\nexport default withUiRules('${componentName}', ${importName}, ${serializeRule(rule)});\n`;

  fs.writeFileSync(filePath, code, 'utf-8');
  return filePath;
}

export function createUiEnhanceResolver(options: UiEnhanceOptions): ComponentResolver {
  const libraryConfig = getLibraryConfig(options.library);
  const usePreset = options.usePreset !== false;

  const customRules = options.rules ?? {};

  const rules: UiRules = {
    ...(usePreset ? getPresetRules(libraryConfig.name) : {}),
    ...customRules
  };

  return {
    type: 'component',
    resolve: (name: string) => {
      const rule = rules[name];
      if (!rule) return;

      const filePath = createEnhancedComponent(name, rule, libraryConfig);
      const styleImport = libraryConfig.importStyle?.(name);
      let versionSuffix = '';
      try {
        const stats = fs.statSync(filePath);
        versionSuffix = `?v=${Math.floor(stats.mtimeMs).toString(36)}`;
      } catch {
        versionSuffix = `?v=${Date.now().toString(36)}`;
      }
      const normalizedFrom = `${filePath.replace(/\\/g, '/')}${versionSuffix}`;
      return {
        name: 'default',
        from: normalizedFrom,
        sideEffects: styleImport || undefined
      };
    }
  };
}

export function createUiEnhance(library: UiLibrary): ComponentResolver {
  return {
    type: 'component',
    resolve: (name: string) => {
      const overrides = toLibraryOverrides(getLibraryUserConfig(library));
      const resolverOptions: UiEnhanceOptions = { library };
      if (overrides?.rules) {
        resolverOptions.rules = overrides.rules;
      }
      if (overrides?.usePreset !== undefined) {
        resolverOptions.usePreset = overrides.usePreset;
      }

      const resolver = createUiEnhanceResolver(resolverOptions);

      if (typeof resolver === 'function') {
        return resolver(name);
      }
      return resolver.resolve(name);
    }
  };
}
